USE [master]
GO
/****** Object:  Database [BookTest]    Script Date: 27.02.2021 0:49:32 ******/
CREATE DATABASE [BookTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BookTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BookTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BookTest] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BookTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BookTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookTest] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BookTest] SET  MULTI_USER 
GO
ALTER DATABASE [BookTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BookTest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BookTest] SET QUERY_STORE = OFF
GO
USE [BookTest]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 27.02.2021 0:49:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[First_Name] [nvarchar](50) NOT NULL,
	[Last_Name] [nvarchar](50) NOT NULL,
	[Patronymic] [nvarchar](50) NOT NULL,
	[Birthyear] [int] NOT NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 27.02.2021 0:49:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Count] [int] NOT NULL,
	[idAuthor] [int] NOT NULL,
	[idGerne] [int] NOT NULL,
 CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Genre]    Script Date: 27.02.2021 0:49:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genre](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_Genre] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Author] FOREIGN KEY([idAuthor])
REFERENCES [dbo].[Author] ([id])
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Author]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Genre] FOREIGN KEY([idGerne])
REFERENCES [dbo].[Genre] ([id])
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Genre]
GO
USE [master]
GO
ALTER DATABASE [BookTest] SET  READ_WRITE 
GO
